### ISSUE TITLE
2.00.00 WebGL : Unsupported?

### ISSUE THREAD

**Issue by webthingee** [fmod/UnityIntegration#18]
Got the latest version of the unitypackage.
Works better than a few days ago.

Build for PC and Mac work fine.
When I switch to Build for WebGL
errors and stays it is unsupported

<img width="787" alt="Unity 2018 3 11f1 Personal - fmodAudioTest unity - FMOD2Test - WebGL (Personal)  Metal  2019-03-31 19-43-08" src="https://user-images.githubusercontent.com/481373/55300668-621e0580-53ed-11e9-9f64-95d0be523ce7.png">

**Comment by fmod-cameron** [comment]
The error message was caused by a missing include, which I have just fixed up in the master branch.

I'm assuming the unsupported platform warning will be related to the error, as WebGL is supported.

**Comment by webthingee** [comment]
Does that mean I can download the package from https://www.fmod.com/download and it will now work? e.g. I am unsure how to use this repo in the project and still get the necessary library.

**Comment by fmod-cameron** [comment]
Not yet, the next release will have this fix and should be out within the next week.

This repo is just used for the source files, you can use these with the libs from the untiypackage you download from our site.

**Comment by webthingee** [comment]
gotcha, I was about to build w/ these files and adding in the lib files I wanted.
Very cool.
The volume sliders I wrote don't see to work in webGL, but the work elseware. Must be related to how the banks are build and managed in webGL.
Thanks for the new code, the info, and the replies @fmod-cameron !

**Comment by fmod-cameron** [comment]
No problem, feel free to post on our Q&A if you get stuck.
https://qa.fmod.com/

**Comment by webthingee** [comment]
@fmod-cameron TOTALLY Works. Had to adjust some Awake code to Start code. But its good as gold!!! Thanks again for the help!!
